spring:
  config:
    import: file:///G:/javaProjects/CONFIG/profiler/profiler-application.yml

  data:
    mongodb:
      host: localhost
      port: 27018
      database: reapi_mongo_db

logging:
  level:
    root: INFO
    com.emat.reapi.ai.configuration: DEBUG
    org.springframework.web.reactive.function.client: TRACE
