spring:
  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        probes:
          enabled: true
        show-details: never
  config:
    import: optional:file:/config/profiler-application.yml
#    in docker, mounted from server file path in opt/

  data:
    mongodb:
      uri: mongodb://profiler_app:${MONGO_PWD}@mongo:27017/profiler?authSource=profiler

logging:
  level:
    root: INFO
    com.emat.reapi.ai.configuration: DEBUG
    org.springframework.web.reactive.function.client: TRACE
